apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: uat
spec:
  type: {{ .Values.service.type }}
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}